import avatarIcon from './images/avatar.png';
import avatarIcon2 from './images/avatar2.png';
export const columnsAppointment = ['Doctor’s Name', 'Date', 'TEST NAME', 'FEES', 'fees', 'Meeting Status'];

export const rowsAppointment = [
    {
        id: '1',
        photo: avatarIcon,
        name: "PCR Test",
        date: "Feb 15, 2020",
        firstName: 'Theresa',
        lastName: 'Webb',
        fees: "$3,500",
        status: "Scheduled",
    },
    {
        id: '2',
        photo: avatarIcon2,
        name: "Antigen Test",
        date: "Feb 15, 2020",
        firstName: 'Darrell',
        lastName: 'Steward',
        fees: "$1,800",
        status: "Scheduled",
    },
    {
        id: '3',
        photo: avatarIcon,
        name: "Diopter check",
        date: "Feb 15, 2020",
        firstName: 'Marvin',
        lastName: 'McKinney',
        fees: "$4,500",
        status: "Scheduled",
    },
    {
        id: '4',
        photo: avatarIcon2,
        name: "PCR Test",
        date: "Feb 15, 2020",
        firstName: 'Theresa',
        lastName: 'Webb',
        fees: "$3,500",
        status: "Scheduled",
    },
    {
        id: '5',
        photo: avatarIcon,
        name: "Antigen Test",
        date: "Feb 15, 2020",
        firstName: 'Darrell',
        lastName: 'Steward',
        fees: "$1,800",
        status: "Scheduled",
    },
    {
        id: '6',
        photo: avatarIcon2,
        name: "Diopter check",
        date: "Feb 15, 2020",
        firstName: 'Marvin',
        lastName: 'McKinney',
        fees: "$4,500",
        status: "Scheduled",
    },
]